#!/bin/sh
# This script allows a 3rd party IDE to use CyElfTool to perform
# the post processing that is necessary to update the *.elf file
# generated by the linker into a complete memory image to use in
# programming the PSoC.
# NOTE: Please provide the path to the CyElfTool.
set buildDir=%PWD%
LAST_EXIT=$?
if [ $LAST_EXIT != 0 ]; then
    exit $LAST_EXIT
fi
cyelftool.exe -C "$1" --flash_row_size 128 --flash_size 32768 --flash_offset 0x00000000 
LAST_EXIT=$?
if [ $LAST_EXIT != 0 ]; then
    exit $LAST_EXIT
fi
