# THIS FILE IS AUTOMATICALLY GENERATED
# Project: D:\Git\microcontroller-test-code\PSOC4000S\biquad.cydsn\biquad.cyprj
# Date: Sat, 09 Sep 2017 22:11:56 GMT
#set_units -time ns
create_clock -name {CyIMO} -period 41.666666666666664 -waveform {0 20.8333333333333} [list [get_pins {ClockBlock/imo}]]
create_clock -name {CyHFClk} -period 41.666666666666664 -waveform {0 20.8333333333333} [list [get_pins {ClockBlock/hfclk}]]
create_clock -name {CySysClk} -period 41.666666666666664 -waveform {0 20.8333333333333} [list [get_pins {ClockBlock/sysclk}]]


# Component constraints for D:\Git\microcontroller-test-code\PSOC4000S\biquad.cydsn\TopDesign\TopDesign.cysch
# Project: D:\Git\microcontroller-test-code\PSOC4000S\biquad.cydsn\biquad.cyprj
# Date: Sat, 09 Sep 2017 22:11:56 GMT
