/***************************************************************/
/*                                                             */
/*      PROJECT NAME :  blink                                  */
/*      FILE         :  interrupt_handlers.c                   */
/*      DESCRIPTION  :  Interrupt Handler                      */
/*      CPU SERIES   :  RL78 - L1A                             */
/*      CPU TYPE     :  R5F11MPG                               */
/*                                                             */
/*      This file is generated by e2 studio.                   */
/*                                                             */
/***************************************************************/                            
                                                                                   
/************************************************************************/
/* Header file generated from device file:                              */
/*    DR5F11MPG.DVF                                                     */
/*    V1.00 (2016/08/22)                                                */
/*    Copyright(C) 2016 Renesas                                         */
/* Tool Version: 3.5.4                                                  */
/* Date Generated: 2016/08/23                                           */
/************************************************************************/
#include "interrupt_handlers.h"

/*
 * INT_WDTI (0x4)
 */
void INT_WDTI (void) { }

/*
 * INT_LVI (0x6)
 */
void INT_LVI (void) { }

/*
 * INT_P0 (0x8)
 */
void INT_P0 (void) { }

/*
 * INT_P1 (0xA)
 */
void INT_P1 (void) { }

/*
 * INT_P2 (0xC)
 */
void INT_P2 (void) { }

/*
 * INT_P3 (0xE)
 */
void INT_P3 (void) { }

/*
 * INT_P4 (0x10)
 */
void INT_P4 (void) { }

/*
 * INT_P5 (0x12)
 */
void INT_P5 (void) { }

/*
 * INT_CSI20/INT_IIC20/INT_ST2 (0x14)
 */
void INT_ST2 (void) { }
//void INT_CSI20 (void) { }
//void INT_IIC20 (void) { }

/*
 * INT_SR2 (0x16)
 */
void INT_SR2 (void) { }

/*
 * INT_SRE2 (0x18)
 */
void INT_SRE2 (void) { }

/*
 * INT_CSI00/INT_IIC00/INT_ST0 (0x1E)
 */
void INT_ST0 (void) { }
//void INT_CSI00 (void) { }
//void INT_IIC00 (void) { }

/*
 * INT_TM00 (0x20)
 */
void INT_TM00 (void) { }

/*
 * INT_SR0 (0x22)
 */
void INT_SR0 (void) { }

/*
 * INT_SRE0/INT_TM01H (0x24)
 */
void INT_TM01H (void) { }
//void INT_SRE0 (void) { }

/*
 * INT_CSI10/INT_IIC10/INT_ST1 (0x26)
 */
void INT_ST1 (void) { }
//void INT_CSI10 (void) { }
//void INT_IIC10 (void) { }

/*
 * INT_SR1 (0x28)
 */
void INT_SR1 (void) { }

/*
 * INT_SRE1/INT_TM03H (0x2A)
 */
void INT_TM03H (void) { }
//void INT_SRE1 (void) { }

/*
 * INT_IICA0 (0x2C)
 */
void INT_IICA0 (void) { }

/*
 * INT_RTIT (0x2E)
 */
void INT_RTIT (void) { }

/*
 * INT_TM01 (0x32)
 */
void INT_TM01 (void) { }

/*
 * INT_TM02 (0x34)
 */
void INT_TM02 (void) { }

/*
 * INT_TM03 (0x36)
 */
void INT_TM03 (void) { }

/*
 * INT_AD (0x38)
 */
void INT_AD (void) { }

/*
 * INT_RTC (0x3A)
 */
void INT_RTC (void) { }

/*
 * INT_IT (0x3C)
 */
void INT_IT (void) { }

/*
 * INT_KR (0x3E)
 */
void INT_KR (void) { }

/*
 * INT_CSI30/INT_IIC30/INT_ST3 (0x40)
 */
void INT_ST3 (void) { }
//void INT_CSI30 (void) { }
//void INT_IIC30 (void) { }

/*
 * INT_SR3 (0x42)
 */
void INT_SR3 (void) { }

/*
 * INT_SRE3 (0x44)
 */
void INT_SRE3 (void) { }

/*
 * INT_TM04 (0x46)
 */
void INT_TM04 (void) { }

/*
 * INT_TM05 (0x48)
 */
void INT_TM05 (void) { }

/*
 * INT_P6 (0x4A)
 */
void INT_P6 (void) { }

/*
 * INT_P7 (0x4C)
 */
void INT_P7 (void) { }

/*
 * INT_CMP0 (0x50)
 */
void INT_CMP0 (void) { }

/*
 * INT_TM06 (0x54)
 */
void INT_TM06 (void) { }

/*
 * INT_TM07 (0x56)
 */
void INT_TM07 (void) { }

/*
 * INT_IT00 (0x58)
 */
void INT_IT00 (void) { }

/*
 * INT_IT01 (0x5A)
 */
void INT_IT01 (void) { }

/*
 * INT_FL (0x62)
 */
void INT_FL (void) { }

/*
 * INT_BRK_I (0x7E)
 */
void INT_BRK_I (void) { }
