/***************************************************************/
/*                                                             */
/*      PROJECT NAME :  blink                                  */
/*      FILE         :  vector_table.c                         */
/*      DESCRIPTION  :  Vector Table                           */
/*      CPU SERIES   :  RL78 - L1A                             */
/*      CPU TYPE     :  R5F11MPG                               */
/*                                                             */
/*      This file is generated by e2 studio.                   */
/*                                                             */
/***************************************************************/                            
                                                                                   
/************************************************************************/
/* Header file generated from device file:                              */
/*    DR5F11MPG.DVF                                                     */
/*    V1.00 (2016/08/22)                                                */
/*    Copyright(C) 2016 Renesas                                         */
/* Tool Version: 3.5.4                                                  */
/* Date Generated: 2016/08/23                                           */
/************************************************************************/
#include "interrupt_handlers.h"

extern void PowerON_Reset (void);

const unsigned char Option_Bytes[]  __attribute__ ((section (".option_bytes"))) = {
	0xef, 0xff, 0xe8, 0x85
};

const unsigned char Security_Id[]  __attribute__ ((section (".security_id"))) = {
	0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00
};

#define VEC          __attribute__ ((section (".vec")))
const void *HardwareVectors[] VEC = {
	// Address 0x0
	PowerON_Reset,
	// Secure for Debugging
	(void*)0xFFFF
};

#define VECT_SECT          __attribute__ ((section (".vects")))
const void *Vectors[] VECT_SECT = {
	//INT_WDTI (0x4)
	INT_WDTI,
	//INT_LVI (0x6)
	INT_LVI,
	//INT_P0 (0x8)
	INT_P0,
	//INT_P1 (0xA)
	INT_P1,
	//INT_P2 (0xC)
	INT_P2,
	//INT_P3 (0xE)
	INT_P3,
	//INT_P4 (0x10)
	INT_P4,
	//INT_P5 (0x12)
	INT_P5,
	//INT_CSI20/INT_IIC20/INT_ST2 (0x14)
	INT_ST2,
	//INT_SR2 (0x16)
	INT_SR2,
	//INT_SRE2 (0x18)
	INT_SRE2,
	// Padding
	(void*)0xFFFF,
	// Padding
	(void*)0xFFFF,
	//INT_CSI00/INT_IIC00/INT_ST0 (0x1E)
	INT_ST0,
	//INT_TM00 (0x20)
	INT_TM00,
	//INT_SR0 (0x22)
	INT_SR0,
	//INT_SRE0/INT_TM01H (0x24)
	INT_TM01H,
	//INT_CSI10/INT_IIC10/INT_ST1 (0x26)
	INT_ST1,
	//INT_SR1 (0x28)
	INT_SR1,
	//INT_SRE1/INT_TM03H (0x2A)
	INT_TM03H,
	//INT_IICA0 (0x2C)
	INT_IICA0,
	//INT_RTIT (0x2E)
	INT_RTIT,
	// Padding
	(void*)0xFFFF,
	//INT_TM01 (0x32)
	INT_TM01,
	//INT_TM02 (0x34)
	INT_TM02,
	//INT_TM03 (0x36)
	INT_TM03,
	//INT_AD (0x38)
	INT_AD,
	//INT_RTC (0x3A)
	INT_RTC,
	//INT_IT (0x3C)
	INT_IT,
	//INT_KR (0x3E)
	INT_KR,
	//INT_CSI30/INT_IIC30/INT_ST3 (0x40)
	INT_ST3,
	//INT_SR3 (0x42)
	INT_SR3,
	//INT_SRE3 (0x44)
	INT_SRE3,
	//INT_TM04 (0x46)
	INT_TM04,
	//INT_TM05 (0x48)
	INT_TM05,
	//INT_P6 (0x4A)
	INT_P6,
	//INT_P7 (0x4C)
	INT_P7,
	// Padding
	(void*)0xFFFF,
	//INT_CMP0 (0x50)
	INT_CMP0,
	// Padding
	(void*)0xFFFF,
	//INT_TM06 (0x54)
	INT_TM06,
	//INT_TM07 (0x56)
	INT_TM07,
	//INT_IT00 (0x58)
	INT_IT00,
	//INT_IT01 (0x5A)
	INT_IT01,
	// Padding
	(void*)0xFFFF,
	// Padding
	(void*)0xFFFF,
	// Padding
	(void*)0xFFFF,
	//INT_FL (0x62)
	INT_FL,
	// Padding
	(void*)0xFFFF,
	// Padding
	(void*)0xFFFF,
	// Padding
	(void*)0xFFFF,
	// Padding
	(void*)0xFFFF,
	// Padding
	(void*)0xFFFF,
	// Padding
	(void*)0xFFFF,
	// Padding
	(void*)0xFFFF,
	// Padding
	(void*)0xFFFF,
	// Padding
	(void*)0xFFFF,
	// Padding
	(void*)0xFFFF,
	// Padding
	(void*)0xFFFF,
	// Padding
	(void*)0xFFFF,
	// Padding
	(void*)0xFFFF,
	//INT_BRK_I (0x7E)
	INT_BRK_I,
};

