/**
 * @file dmx512_rd.c
 * @date 2016-07-08
 *
 * NOTE:
 * This file is generated by DAVE. Any manual modification done to this file will be lost when the code is regenerated.
 *
 * @cond
 ***********************************************************************************************************************
 * DMX512_RD v4.0.16 - Provides user configuration for DMX512 Application Stack.
 *                    Note: DIGITAL_IO APP is required to select DMX512 input as well as Accurate Break Detection input.
 *
 * Copyright (c) 2015-2016, Infineon Technologies AG
 * All rights reserved.                        
 *                                             
 * Redistribution and use in source and binary forms, with or without modification,are permitted provided that the           
 * following conditions are met:   
 *                                                                              
 *   Redistributions of source code must retain the above copyright notice, this list of conditions and the  following   
 *   disclaimer.                        
 * 
 *   Redistributions in binary form must reproduce the above copyright notice, this list of conditions and the    
 *   following disclaimer in the documentation and/or other materials provided with the distribution.     
 *                         
 *   Neither the name of the copyright holders nor the names of its contributors may be used to endorse or promote 
 *   products derived from this software without specific prior written permission. 
 *                                             
 * THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS IS" AND ANY EXPRESS OR IMPLIED WARRANTIES,  
 * INCLUDING, BUT NOT LIMITED TO, THE IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE   
 * DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT HOLDER OR CONTRIBUTORS BE LIABLE  FOR ANY DIRECT, INDIRECT, INCIDENTAL,  
 * SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR        
 * SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY,      
 * WHETHER IN CONTRACT, STRICT LIABILITY,OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT  OF THE   
 * USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.    
 *                                                                              
 * To improve the quality of the software, users are encouraged to share modifications, enhancements or bug fixes       
 * with Infineon Technologies AG (dave@infineon.com).        
 ***********************************************************************************************************************
 *
 * Change History
 * --------------
 * 2015-02-16:
 *     - Initial version for DAVEv4. <BR>
 * 2015-05-08:
 *     - Minor bug fix in DMX512_RD_Capt_IRQHandler(). <BR>
 *
 * 2015-08-25:
 *     - Supported XMC14 device and added Interrupt Source Selection code for XMC14.<br>
 * 2016-07-08:
 *     - Fixed incorrect case for an included header.<br>
 *
 * @endcond 
 *
 */

/***********************************************************************************************************************
 * HEADER FILES                                                                                                      
 **********************************************************************************************************************/
#include "dmx512_rd.h"

/***********************************************************************************************************************
 * MACROS
 **********************************************************************************************************************/

/***********************************************************************************************************************
 * LOCAL DATA
 **********************************************************************************************************************/

/***********************************************************************************************************************
 * LOCAL ROUTINES
 **********************************************************************************************************************/

/***********************************************************************************************************************
* API IMPLEMENTATION
***********************************************************************************************************************/
/*  API to retrieve version of the APP */
DAVE_APP_VERSION_t DMX512_RD_GetAppVersion(void)
{
  DAVE_APP_VERSION_t version;
  version.major = (uint8_t)DMX512_RD_MAJOR_VERSION;
  version.minor = (uint8_t)DMX512_RD_MINOR_VERSION;
  version.patch = (uint8_t)DMX512_RD_PATCH_VERSION;

  return (version);
}

/*  Initializes the uart and ccu4 slice peripherals based on UI configuration */
DMX512_RD_STATUS_t DMX512_RD_Init(DMX512_RD_t *const handle)
{
  DMX512_RD_STATUS_t status;
  status = DMX512_RD_STATUS_SUCCESS;
  XMC_USIC_CH_t *const usic = (XMC_USIC_CH_t *)handle->uart_ch;

  XMC_ASSERT("DMX512_RD APP handle function pointer uninitialized", (handle != NULL));


#if (1U == DMX512_RD_ACCURATE_BREAK_DET_USED)
  if (true == handle->acc_break_det)
  {
    status |= (DMX512_RD_STATUS_t) GLOBAL_CCU4_Init(handle->ccu4globalapp);
  }
#endif

  if (DMX512_RD_STATUS_SUCCESS == status)
  {
    /************************************************
    * Slot data reception using USIC channel (UART) *
    *************************************************/
    /* Ungating the peripheral clock */
    XMC_USIC_Enable(handle->uart_module);
    /* Initialize USIC channel in UART mode*/
    XMC_UART_CH_Init(usic, &handle->uart_config);
    /* DX0 input signal selection */
    XMC_USIC_CH_SetInputSource(usic, XMC_USIC_CH_INPUT_DX0, handle->uart_dx0_mux);
    /* Configure DX3 & DX5 input stage for XMC1000 devices */
#if UC_FAMILY == XMC1
    /* DX3 input signal selection */
    XMC_USIC_CH_SetInputSource(usic, XMC_USIC_CH_INPUT_DX3, handle->uart_dx3_mux);
    /* DX5 input signal selection */
    XMC_USIC_CH_SetInputSource(usic, XMC_USIC_CH_INPUT_DX5, handle->uart_dx5_mux);
#endif

    /* FIFO (Rx) configuration: Data pointer = 2, size = 2, limit = 1*/
    XMC_USIC_CH_RXFIFO_Configure(usic, 0U, XMC_USIC_CH_FIFO_SIZE_2WORDS, 1U);
    /* Service request configuration for Rx FIFO standard buffer interrupt*/
    XMC_USIC_CH_RXFIFO_SetInterruptNodePointer(usic, XMC_USIC_CH_RXFIFO_INTERRUPT_NODE_POINTER_STANDARD,
    		                                    handle->uart_events_sr_no);

    if (false == handle->acc_break_det)
    {
      /* Enable interrupt at SBD (Synchronization BREAK Detection) */
      XMC_UART_CH_EnableEvent(usic, (uint32_t)XMC_UART_CH_EVENT_SYNCHRONIZATION_BREAK);
      /* Service request configuration for protocol interrupt */
      XMC_USIC_CH_SetInterruptNodePointer(usic, XMC_USIC_CH_INTERRUPT_NODE_POINTER_PROTOCOL, handle->uart_events_sr_no);
    }
    /* Interrupt configuration for UART */
#if (UC_FAMILY == XMC1)
    NVIC_SetPriority(handle->uart_irq_no, handle->uart_irq_priority);
#else
    NVIC_SetPriority(handle->uart_irq_no, NVIC_EncodePriority(NVIC_GetPriorityGrouping(),
                              handle->uart_irq_priority, handle->uart_irq_subpriority));
#endif
#if (UC_SERIES == XMC14)
      XMC_SCU_SetInterruptControl((IRQn_Type)handle->uart_irq_no, (XMC_SCU_IRQCTRL_t)handle->uart_irq_source);
#endif
    NVIC_EnableIRQ(handle->uart_irq_no);

    /* Start UART */
    XMC_UART_CH_Start(usic);

#if (1U == DMX512_RD_ACCURATE_BREAK_DET_USED)
    if (true == handle->acc_break_det)
    {
/******************************************************
* Accurate break detection using CCU4 slice (capture) *
*******************************************************/
      XMC_CCU4_SLICE_CaptureInit(handle->capt_slice, &handle->capt_config);

      /* Input selection, edge trigger, level trigger and LPF cycles configuration*/
      XMC_CCU4_SLICE_ConfigureEvent(handle->capt_slice, XMC_CCU4_SLICE_EVENT_0, &handle->capt_event0_config);
      XMC_CCU4_SLICE_ConfigureEvent(handle->capt_slice, XMC_CCU4_SLICE_EVENT_1, &handle->capt_event1_config);

      /* Timer started at Falling edge (Event0), Timer stopped at Rising Edge (Event 1) */
      XMC_CCU4_SLICE_StartConfig(handle->capt_slice, XMC_CCU4_SLICE_EVENT_0,
                                 XMC_CCU4_SLICE_START_MODE_TIMER_START_CLEAR);
      XMC_CCU4_SLICE_StopConfig(handle->capt_slice, XMC_CCU4_SLICE_EVENT_1, XMC_CCU4_SLICE_END_MODE_TIMER_STOP);

      /* External capture0  triggered by Event0 */
      XMC_CCU4_SLICE_Capture0Config(handle->capt_slice, XMC_CCU4_SLICE_EVENT_0);
      /* External capture0  triggered by Event1 */
      XMC_CCU4_SLICE_Capture1Config(handle->capt_slice, XMC_CCU4_SLICE_EVENT_1);

      /* Timer single-shot mode */
      XMC_CCU4_SLICE_SetTimerRepeatMode(handle->capt_slice, XMC_CCU4_SLICE_TIMER_REPEAT_MODE_REPEAT);

      /* Enable capture slice (clearing a slice from idle mode) */
      XMC_CCU4_EnableClock(handle->capt_module, handle->capt_slice_no);

      /* Event1 service node configuration */
      XMC_CCU4_SLICE_SetInterruptNode(handle->capt_slice, XMC_CCU4_SLICE_IRQ_ID_EVENT1, handle->capt_event_sr_no);
      /* Event1 interrupt enable */
      XMC_CCU4_SLICE_EnableEvent(handle->capt_slice, XMC_CCU4_SLICE_IRQ_ID_EVENT1);

      /* Interrupt configuration for Capture */
#if (UC_FAMILY == XMC1)
      NVIC_SetPriority(handle->capt_irq_no, handle->capt_irq_priority);
#else
      NVIC_SetPriority(handle->capt_irq_no, NVIC_EncodePriority(NVIC_GetPriorityGrouping(),
  		   	   	    handle->capt_irq_priority, handle->capt_irq_subpriority));
#endif
#if (UC_SERIES == XMC14)
      XMC_SCU_SetInterruptControl((IRQn_Type)handle->capt_irq_no, (XMC_SCU_IRQCTRL_t)handle->capt_irq_source);
#endif
      NVIC_EnableIRQ(handle->capt_irq_no);
    }
#endif
  }
  return (status);
}

/*  Configures starting slot number */
DMX512_RD_STATUS_t DMX512_RD_ConfigStartSlotNo(DMX512_RD_t *const handle, uint32_t slot_num)
{
  DMX512_RD_STATUS_t status;
  status = DMX512_RD_STATUS_FAILURE;

  XMC_ASSERT("DMX512_RD APP handle function pointer uninitialized", (handle != NULL));
  XMC_ASSERT("DMX512_RD APP starting slot number invalid", (slot_num < DMX512_RD_START_SLOT) ||
              (slot_num > DMX512_RD_FINAL_SLOT));

  if ((slot_num >= DMX512_RD_START_SLOT) && (slot_num <= DMX512_RD_FINAL_SLOT))
  {
    if ((slot_num + (handle->no_of_slots)) <= DMX512_RD_FINAL_SLOT)
    {
      handle->start_slot_num = (uint16_t)slot_num;
      status = DMX512_RD_STATUS_SUCCESS;
    }
  }
  return (status);
}

#if (1U == DMX512_RD_ACCURATE_BREAK_DET_USED)
/*  Detects accurate break using CCU4 slice, then it enables UART peripheral to receive dmx slice data */
void DMX512_RD_Capt_IRQHandler(DMX512_RD_t *handle)
{
  uint32_t cap_count;
  cap_count = XMC_CCU4_SLICE_GetCaptureRegisterValue(handle->capt_slice, 3U) & CCU4_CC4_CV_CAPTV_Msk;

  if (cap_count > DMX512_RD_CAPT_BREAK_COUNT) /* 88uS */
  {
    handle->current_slot_num = 0U;
    while(false == XMC_USIC_CH_RXFIFO_IsEmpty(handle->uart_ch))
    {
    	*(handle->rx_array_ptr) = (uint8_t)XMC_USIC_CH_RXFIFO_GetData(handle->uart_ch);
    }

    /* Enable USIC Standard Receive Buffer interrupt */
    XMC_USIC_CH_RXFIFO_EnableEvent(handle->uart_ch, (uint32_t)XMC_USIC_CH_RXFIFO_EVENT_CONF_STANDARD);
  }
  else
  {
	  /* Non-break state */
  }
}
#endif

/*  Receives dmx slice data */
void DMX512_RD_UART_IRQHandler(DMX512_RD_t *handle)
{
  uint16_t read_byte;
  read_byte = 0U;
  
  if ((XMC_USIC_CH_RXFIFO_GetEvent(handle->uart_ch) & USIC_CH_TRBSR_SRBI_Msk) == USIC_CH_TRBSR_SRBI_Msk)
  {
    read_byte = XMC_USIC_CH_RXFIFO_GetData(handle->uart_ch);
    XMC_USIC_CH_RXFIFO_ClearEvent(handle->uart_ch, (uint32_t)XMC_USIC_CH_RXFIFO_EVENT_STANDARD);
    handle->current_slot_num = handle->current_slot_num + 1U;
  }
  if (handle->acc_break_det == false)
  {
    if ((XMC_UART_CH_GetStatusFlag(handle->uart_ch) & USIC_CH_PSR_ASCMode_SBD_Msk) == USIC_CH_PSR_ASCMode_SBD_Msk)
    {
      XMC_UART_CH_ClearStatusFlag(handle->uart_ch, (uint32_t)XMC_UART_CH_STATUS_FLAG_SYNCHRONIZATION_BREAK_DETECTED);
      handle->current_slot_num = 0U;
      while(false == XMC_USIC_CH_RXFIFO_IsEmpty(handle->uart_ch))
      {
    	  *(handle->rx_array_ptr) = (uint8_t)XMC_USIC_CH_RXFIFO_GetData(handle->uart_ch);
      }
      /* Enable USIC Standard Receive Buffer interrupt */
      XMC_USIC_CH_RXFIFO_EnableEvent(handle->uart_ch, (uint32_t)XMC_USIC_CH_RXFIFO_EVENT_CONF_STANDARD);
    }
  }
  if ((handle->current_slot_num-1U) >= (handle->start_slot_num))
  {
    if ((handle->current_slot_num-1U) < ((handle->start_slot_num) + (handle->no_of_slots)))
    {
      *((handle->rx_array_ptr) + ((handle->current_slot_num - 1U) - handle->start_slot_num)) =
        (uint8_t)(read_byte & 0xFFU);
      if ((handle->current_slot_num) == ((handle->start_slot_num) + (handle->no_of_slots)))
      {
      	/* Disable USIC Standard Receive Buffer interrupt */
        XMC_USIC_CH_RXFIFO_DisableEvent(handle->uart_ch, (uint32_t)XMC_USIC_CH_RXFIFO_EVENT_CONF_STANDARD);
        /* Clear receive buffer status */
        XMC_USIC_CH_RXFIFO_ClearEvent(handle->uart_ch, (uint32_t)((uint32_t)XMC_USIC_CH_RXFIFO_EVENT_STANDARD |
                                     (uint32_t)XMC_USIC_CH_RXFIFO_EVENT_ERROR |(uint32_t)XMC_USIC_CH_RXFIFO_EVENT_ALTERNATE));
        XMC_USIC_CH_RXFIFO_Flush(handle->uart_ch);
        /* Slot data reception is successful, calling user Callback function */
        if (handle->callback_function != NULL)
        {
          handle->callback_function();
        }
      }
    }
  }
}

