/* MAIN.C file
 * 
 * Copyright (c) 2002-2005 STMicroelectronics
 */

#include "stm8s_conf.h"

main()
{
	CLK_SYSCLKConfig(CLK_PRESCALER_HSIDIV4); // 4 MHz clock
	
	//GPIO_Init(GPIOD, GPIO_PIN_0, GPIO_MODE_OUT_PP_LOW_FAST);
	//GPIO_Init(GPIOD, GPIO_PIN_2, GPIO_MODE_OUT_PP_LOW_FAST);
	
	TIM1_TimeBaseInit(0, TIM1_COUNTERMODE_UP, 255, 0);
	TIM1_OC1Init(TIM1_OCMODE_PWM2, 
							 TIM1_OUTPUTSTATE_ENABLE, 
							 TIM1_OUTPUTNSTATE_ENABLE, 
							 0, 
							 TIM1_OCPOLARITY_HIGH, 
							 TIM1_OCNPOLARITY_LOW, 
							 TIM1_OCIDLESTATE_SET,
							 TIM1_OCNIDLESTATE_RESET); 
							 
	TIM1_OC2Init(TIM1_OCMODE_PWM2, 
							 TIM1_OUTPUTSTATE_ENABLE, 
							 TIM1_OUTPUTNSTATE_ENABLE, 
							 0, 
							 TIM1_OCPOLARITY_HIGH, 
							 TIM1_OCNPOLARITY_LOW, 
							 TIM1_OCIDLESTATE_SET,
							 TIM1_OCNIDLESTATE_RESET); 
							 
	TIM1_OC3Init(TIM1_OCMODE_PWM2, 
							 TIM1_OUTPUTSTATE_ENABLE, 
							 TIM1_OUTPUTNSTATE_ENABLE, 
							 0, 
							 TIM1_OCPOLARITY_HIGH, 
							 TIM1_OCNPOLARITY_LOW, 
							 TIM1_OCIDLESTATE_SET,
							 TIM1_OCNIDLESTATE_RESET); 
	
	TIM1_Cmd(ENABLE);
	
	TIM1_CtrlPWMOutputs(ENABLE);
	
	UART2_Init(250000, 
						 UART2_WORDLENGTH_8D, 
						 UART2_STOPBITS_1, 
						 UART2_PARITY_NO, 
						 UART2_SYNCMODE_CLOCK_DISABLE,
						 UART2_MODE_RX_ENABLE);
						 
	UART2_ITConfig(UART2_IT_RXNE_OR, ENABLE);
	UART2_ITConfig(UART2_IT_RXNE, ENABLE);
	
	UART2_Cmd(ENABLE);
	enableInterrupts();
	while (1)
	{
		wfi();
	}
}