# THIS FILE IS AUTOMATICALLY GENERATED
# Project: D:\Git\microcontroller-test-code\PSOC4000S\debugTest.cydsn\debugTest.cyprj
# Date: Sun, 01 Oct 2017 06:46:15 GMT
#set_units -time ns
create_clock -name {CyILO} -period 25000 -waveform {0 12500} [list [get_pins {ClockBlock/ilo}]]
create_clock -name {CyLFClk} -period 25000 -waveform {0 12500} [list [get_pins {ClockBlock/lfclk}]]
create_clock -name {CyIMO} -period 41.666666666666664 -waveform {0 20.8333333333333} [list [get_pins {ClockBlock/imo}]]
create_clock -name {CyHFClk} -period 41.666666666666664 -waveform {0 20.8333333333333} [list [get_pins {ClockBlock/hfclk}]]
create_clock -name {CySysClk} -period 41.666666666666664 -waveform {0 20.8333333333333} [list [get_pins {ClockBlock/sysclk}]]


# Component constraints for D:\Git\microcontroller-test-code\PSOC4000S\debugTest.cydsn\TopDesign\TopDesign.cysch
# Project: D:\Git\microcontroller-test-code\PSOC4000S\debugTest.cydsn\debugTest.cyprj
# Date: Sun, 01 Oct 2017 06:46:14 GMT
