/*******************************************************************************
* File Name: project.h
* 
* PSoC Creator  4.1 Update 1
*
* Description:
* It contains references to all generated header files and should not be modified.
* This file is automatically generated by PSoC Creator.
*
********************************************************************************
* Copyright (c) 2007-2017 Cypress Semiconductor.  All rights reserved.
* You may use this file only in accordance with the license, terms, conditions, 
* disclaimers, and limitations in the end user license agreement accompanying 
* the software package with which this file was provided.
********************************************************************************/

#include "cyfitter_cfg.h"
#include "cydevice_trm.h"
#include "cyfitter.h"
#include "cydisabledsheets.h"
#include "UART.h"
#include "UART_SPI_UART.h"
#include "UART_PINS.h"
#include "UART_SPI_UART_PVT.h"
#include "UART_PVT.h"
#include "UART_BOOT.h"
#include "RED.h"
#include "Clock_1.h"
#include "BLUE.h"
#include "GREEN.h"
#include "RedPin.h"
#include "RedPin_aliases.h"
#include "BluePin.h"
#include "BluePin_aliases.h"
#include "GreenPin.h"
#include "GreenPin_aliases.h"
#include "UART_ISR.h"
#include "ADC_1_Configuration.h"
#include "ADC_1_Adc.h"
#include "ADC_1_Structure.h"
#include "UART_SCBCLK.h"
#include "UART_rx.h"
#include "UART_rx_aliases.h"
#include "ADC_1_ISR.h"
#include "CyFlash.h"
#include "CyLib.h"
#include "cyPm.h"
#include "cytypes.h"
#include "cypins.h"
#include "core_cm0plus_psoc4.h"
#include "CyLFClk.h"

/*[]*/

